feat: add service mesh
particuleio/formations pull request #15
Opened 2020-11-10 10:44 UTC by ArchiFleKs

2020-11-10 11:22 UTC, rguichard requested changes
There is a space before and after `:`

You should look for missing `è é à ê ô ù ë ...` ;)

2020-11-10 11:22 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Pas d'objets natifs pour faire du routage applicatif poussé
s/plural/singular

2020-11-10 11:22 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Permet la configuration de règles de routage applicative
applicatif

2020-11-10 11:22 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Authentification et authorization
English or French ?

2020-11-10 11:22 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Routage du trafic via des règles applicative
applicatives

2020-11-10 11:35 UTC, ArchiFleKs commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Permet la configuration de règles de routage applicative
ce sont les règles qui sont applicatives non ?

2020-11-10 11:36 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Permet la configuration de règles de routage applicative
non c'est le routage qui est applicatif

2020-11-10 11:36 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Permet la configuration de règles de routage applicative
les deux sont bonnes. Mais si c'est les règles, il faut accordé au pluriel

2020-11-12 08:43 UTC, rguichard commented
Could you rebase and squash ?

2020-11-16 10:25 UTC, ArchiFleKs commented
@rguichard can we merge this

2020-11-16 10:45 UTC, rguichard commented on cours/containers/kubernetes/k8s-service-mesh.fr.md
> +- Pas d'objets natifs pour faire du routage applicatif poussé
Still pending : "pas d'objet natif"

2020-11-16 10:52 UTC, rguichard commented
Could you rebase to take mergify changes into account?

2020-11-16 14:08 UTC, ArchiFleKs commented
done

2020-11-16 14:18 UTC, rguichard approved these changes
lgtm

2020-11-16 14:19 UTC, merged