feat: add istio course
particuleio/formations pull request #17
Opened 2020-11-10 11:17 UTC by ArchiFleKs

2020-11-17 16:09 UTC, ArchiFleKs commented
This is only the course I'll add TPs in separate PR

2020-11-18 17:10 UTC, ArchiFleKs commented
Actually, TPs are in this PR. This would need to be merged tomorrow.

2020-11-18 17:20 UTC, rguichard reviewed
space before `:`
space before `:`
space before `:`
space before `:`
space before `:`
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-introduction.fr.md
> +- Service enregistrés avec Consul
"services enregistrés" ?

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-introduction.fr.md
> +- Fourni une implémentation du concept de service mesh
fournit

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-introduction.fr.md
> +- Simplifie la mise en place de mise à jour automatiques :
mises

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-introduction.fr.md
> +- Load balancing  TCP, GRPC, HTTP et websocket
gRPC

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +- Plan de donnée : composé de proxy [Envoy](https://www.envoyproxy.io/)
- données

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +- Plan de contrôle: `Istiod` qui pilote la configuration du plan de donnée
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +- un ou plusieurs cluster
clusters

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +Multi cluster:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +d'un même pods. Dans un mesh Istio, chaque pods dispose d'un conteneur Envoy
pod

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-architecture.fr.md
> +- automatiquement via webhook + CNI: recommandée
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-observability.fr.md
> +Istio fournit par défaut un service de télémétrie pour toutes les communication au sein du mesh:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-observability.fr.md
> +- Métriques applicative: dashboard et compatibilité [prometheus](https://prometheus.io/)
applicatives :

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-observability.fr.md
> +- Traçage applicatif : integration avec les solutions les plus utilisées:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +[mTLS](https://en.wikipedia.org/wiki/Mutual_authentication): mutual TLS entre
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +- End User: via des fournisseur d'identités compatibles avec [OpenID connect](https://openid.net/connect/):
fournisseurs

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +existe 3 modes:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +S'appliquent:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +
space before `:` for the three previous lines

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-security.fr.md
> +- Fonctionnent avec les protocoles HTTP, HTTPS, HTTP2, GRPC et TCP
gRPC

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-traffic.fr.md
> +Routage entre deux versions d'un même service avec pourcentage:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-traffic.fr.md
> +- Techniques de répartition de charge:
space before `:`

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-traffic.fr.md
> +la consommation CPU/RAM des sidecar peut devenir non négligeable.
sidecars

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-traffic.fr.md
> +- Circuit Breakers : permettent de limiter le nombre de connections à un service en fonction de paramètres afin d'éviter une surcharge
connexions

2020-11-18 17:20 UTC, rguichard commented on cours/containers/istio/istio-traffic.fr.md
> +Fault Injection:
space before `:`

2020-11-18 17:22 UTC, ArchiFleKs commented on cours/containers/istio/istio-introduction.fr.md
> +- Simplifie la mise en place de mise à jour automatiques :
la mise ?

2020-11-18 17:22 UTC, ArchiFleKs commented on cours/containers/istio/istio-introduction.fr.md
> +- Simplifie la mise en place de mise à jour automatiques :
une mise en place

2020-11-18 17:23 UTC, ArchiFleKs commented on cours/containers/istio/istio-introduction.fr.md
> +- Simplifie la mise en place de mise à jour automatiques :
les mises a jour ok ^^

2020-11-20 10:12 UTC, rguichard requested changes
A dedicated Vagrant env should be created for istio.

2020-11-20 10:24 UTC, rguichard approved these changes
lgtm

2020-11-20 10:24 UTC, merged